modLoader="javafml"
loaderVersion="[4,)"
license="Not specified"

[[mods]]
modId="meeptech"
version="1.0.0"
displayName="MeepTech"
displayURL="https://mcreator.net"
credits=""
authors="Meep"

# Start of user code block mod configuration
# End of user code block mod configuration


# Start of user code block custom mixins
# End of user code block custom mixins

[[dependencies.meeptech]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.190,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.meeptech]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration